import './globals.css'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'
import Feature from '../../components/Feature'
import Grid from '../../components/Grid'
import Page from '../../components/Page'
import Teaser from '../../components/Teaser'
import EmailTemplate from '../../components/EmailTemplate'
import StoryblokProvider from '../../components/StoryblokProvider'

const components = {
  feature: Feature,
  grid: Grid,
  page: Page,
  teaser: Teaser,
  'email-template': EmailTemplate,
}
export function loadStoryblok() {
  storyblokInit({
    accessToken: process.env.NEXT_PUBLIC_STORYBLOK_API_TOKEN,
    use: [apiPlugin],
    region: '',
    components,
  })
}
loadStoryblok()

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoryblokProvider>
  )
}
